# The recipes to use for all environments, override at environment level if
# need be.  The recipes to use when bootstrapping each environment will be
# under the bootstrap key.  These are kept separate to make it easy to tear
# down an environment without breaking terraform mid-destroy.  Most new
# deployments will have all recipes under a single key (Default), but the use
# of multiple keys to segment your infrastructure is useful as it grows larger
#
recipes:
  bootstrap:
  default:

# Environment specific overrides for recipes.  You can also put these where you put other
# overrides, but they are here as a convenience to keep recipe overrides close
# to the defaults defined above
#
environments:
