# Optional configuration for controlling the behavior of the atmos runtime

# Sets a prefix on the root keys when passed into terraform as a var value
var_prefix:

# Disable module fetch from convenience plan/apply commandss
disable_auto_modules: false

# Configure the mechanism that allows terraform to callback into atmos
ipc:
  # Disables all IPC callbacks into atmos from terraform
  disable: false
  # Configures the notify IP callback
  notify:
    # Disable notify callbacks
    disable: false

# Configure the integrated otp mechanism
otp:
  # The file where otp secrets are stored
  secret_file: ~/.atmos.yml

# Configure the template generator
generate:
  # The file storing the record of each generated template
  state_file: .atmos-templates.yml

# Configure the UI components
ui:
  # Configures UI notifications
  notify:
    # Disable notifications
    disable: false
    # Force notifications to never be modal
    disable_modal: false
    # Set a custom command for notifications, embedded {{title|message|modal}}
    # will be replaced with the value passed from terraform
    command:
    # Force notifications inline in atmos' stdout output rather than launching
    # a GUI notification
    force_inline: false

# Ths list of plugin gems to load when running atmos
plugins:
#   - atmos-pro

# Configure terraform execution details
terraform:
  # By default, all terraform plugins are placed in a directory so they can be
  # reused across all envs/groups.  This can be disabled here (you can also
  # override using the terraform cli options for plugins)
  disable_shared_plugins: false
